import asyncio
import hashlib
import hmac
import json
import os
import secrets
import sqlite3
import time
from contextlib import asynccontextmanager, contextmanager
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request, Response, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError, VerificationError


BASE_DIR = Path(__file__).resolve().parent
DATABASE_PATH = Path(os.getenv("DATABASE_PATH", str(BASE_DIR / "data" / "relationship.sqlite3")))
DATABASE_URL = os.getenv("DATABASE_URL")
VALID_PEOPLE = {"aditya", "tishu"}
PEOPLE = {"aditya": "Aditya", "tishu": "Tishu"}
SESSION_COOKIE = "aditya_tishu_session"
SESSION_SECONDS = 60 * 60 * 24 * 30
PASSWORD_ROUNDS = 310_000
password_hasher = PasswordHasher()
ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000,http://localhost:5500,http://127.0.0.1:5500",
    ).split(",")
    if origin.strip()
]


class DatabaseConnection:
    def __init__(self, connection, is_postgres: bool):
        self.connection = connection
        self.is_postgres = is_postgres

    def execute(self, query: str, parameters=()):
        if self.is_postgres:
            query = query.replace("?", "%s")
        return self.connection.execute(query, parameters)

    def __enter__(self):
        self.connection.__enter__()
        return self

    def __exit__(self, exception_type, exception, traceback):
        return self.connection.__exit__(exception_type, exception, traceback)

    def close(self):
        self.connection.close()


def connect_db():
    if DATABASE_URL:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError("Install psycopg to use DATABASE_URL.") from error
        connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return DatabaseConnection(connection, is_postgres=True)

    DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DATABASE_PATH, timeout=10)
    connection.row_factory = sqlite3.Row
    return DatabaseConnection(connection, is_postgres=False)


@contextmanager
def database():
    connection = connect_db()
    try:
        with connection:
            yield connection
    finally:
        connection.close()


def initialize_db():
    with database() as connection:
        message_id_type = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if DATABASE_URL
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        statements = (
            f"""CREATE TABLE IF NOT EXISTS messages (
                id {message_id_type},
                sender TEXT NOT NULL,
                sender_id TEXT,
                text TEXT NOT NULL,
                created_at TEXT NOT NULL,
                deleted_at TEXT,
                deleted_by TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS sign_in_phrases (
                person TEXT PRIMARY KEY,
                salt TEXT NOT NULL,
                phrase_hash TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                person TEXT NOT NULL,
                expires_at BIGINT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS reactions (
                message_id BIGINT NOT NULL,
                person TEXT NOT NULL,
                emoji TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                PRIMARY KEY (message_id, person)
            )""",
            """CREATE TABLE IF NOT EXISTS app_settings (
                setting_key TEXT PRIMARY KEY,
                setting_value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS profiles (
                person TEXT PRIMARY KEY,
                display_name TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""",
            f"""CREATE TABLE IF NOT EXISTS postcards (
                id {message_id_type},
                sender_id TEXT NOT NULL,
                recipient_id TEXT NOT NULL,
                text TEXT NOT NULL,
                created_at TEXT NOT NULL,
                reveal_at TEXT NOT NULL,
                opened_at TEXT
            )""",
            "CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at)",
            "CREATE INDEX IF NOT EXISTS idx_reactions_message_id ON reactions (message_id)",
            "CREATE INDEX IF NOT EXISTS idx_postcards_recipient_reveal ON postcards (recipient_id, reveal_at)",
        )
        for statement in statements:
            connection.execute(statement)
        connection.execute("DELETE FROM postcards WHERE opened_at IS NOT NULL")
        if DATABASE_URL:
            existing_columns = {
                row["column_name"]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns WHERE table_name = 'messages'"
                ).fetchall()
            }
        else:
            existing_columns = {
                row["name"]
                for row in connection.execute("PRAGMA table_info(messages)").fetchall()
            }
        if "deleted_at" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN deleted_at TEXT")
        if "deleted_by" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN deleted_by TEXT")
        if "sender_id" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN sender_id TEXT")
        for person, name in PEOPLE.items():
            profile_exists = connection.execute(
                "SELECT 1 FROM profiles WHERE person = ?", (person,)
            ).fetchone()
            if not profile_exists:
                connection.execute(
                    "INSERT INTO profiles (person, display_name, updated_at) VALUES (?, ?, ?)",
                    (person, name, datetime.now(timezone.utc).isoformat()),
                )
            connection.execute(
                "UPDATE messages SET sender_id = ? WHERE sender = ? AND sender_id IS NULL",
                (person, name),
            )
        for person, phrase in (("aditya", "I'm Aditya"), ("tishu", "I'm Tishu")):
            exists = connection.execute(
                "SELECT 1 FROM sign_in_phrases WHERE person = ?", (person,)
            ).fetchone()
            if not exists:
                salt, phrase_hash = hash_phrase(phrase)
                connection.execute(
                    "INSERT INTO sign_in_phrases (person, salt, phrase_hash) VALUES (?, ?, ?)",
                    (person, salt, phrase_hash),
                )
        setting_exists = connection.execute(
            "SELECT 1 FROM app_settings WHERE setting_key = ?", ("welcome_sentence",)
        ).fetchone()
        if not setting_exists:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?)",
                ("welcome_sentence", "A little hello from Delhi", datetime.now(timezone.utc).isoformat()),
            )


@asynccontextmanager
async def lifespan(_app: FastAPI):
    initialize_db()
    yield


app = FastAPI(title="Aditya & Tishu", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Content-Type"],
)


class ChatMessage(BaseModel):
    text: str = Field(min_length=1, max_length=300)


class LoginRequest(BaseModel):
    sentence: str = Field(min_length=1, max_length=200)


class ChangeSentenceRequest(BaseModel):
    current_sentence: str = Field(min_length=1, max_length=200)
    new_sentence: str = Field(min_length=8, max_length=200)


class SettingRequest(BaseModel):
    value: str = Field(min_length=1, max_length=300)


class DisplayNameRequest(BaseModel):
    display_name: str = Field(min_length=1, max_length=40)


class PostcardRequest(BaseModel):
    text: str = Field(min_length=1, max_length=500)


def hash_phrase(phrase: str, salt: bytes | None = None):
    if salt is None:
        return "", password_hasher.hash(phrase.strip().casefold())
    salt = salt or secrets.token_bytes(16)
    phrase_hash = hashlib.pbkdf2_hmac(
        "sha256", phrase.strip().casefold().encode("utf-8"), salt, PASSWORD_ROUNDS
    )
    return salt.hex(), phrase_hash.hex()


def phrase_matches(phrase: str, salt: str, phrase_hash: str):
    if phrase_hash.startswith("$argon2"):
        try:
            password_hasher.verify(phrase_hash, phrase.strip().casefold())
            return True
        except (VerifyMismatchError, VerificationError):
            return False
    _, candidate_hash = hash_phrase(phrase, bytes.fromhex(salt))
    return hmac.compare_digest(candidate_hash, phrase_hash)


def needs_hash_upgrade(phrase_hash: str):
    return not phrase_hash.startswith("$argon2")


def session_person(token: str | None):
    if not token:
        return None
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    with database() as connection:
        row = connection.execute(
            "SELECT person, expires_at FROM sessions WHERE token_hash = ?", (token_hash,)
        ).fetchone()
        if row and row["expires_at"] <= int(time.time()):
            connection.execute("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))
            return None
    return row["person"] if row else None


def authenticated_person(request: Request):
    person = session_person(request.cookies.get(SESSION_COOKIE))
    if not person:
        raise HTTPException(status_code=401, detail="Sign in to open your little corner.")
    return person


def require_owner(request: Request, person: str):
    validate_person(person)
    signed_in_person = authenticated_person(request)
    if signed_in_person != person:
        raise HTTPException(status_code=403, detail="That plan belongs to the other person.")


def validate_person(person: str):
    if person not in VALID_PEOPLE:
        raise HTTPException(status_code=404, detail="That person isn't on this little map.")


def profile_name(connection, person: str):
    row = connection.execute(
        "SELECT display_name FROM profiles WHERE person = ?", (person,)
    ).fetchone()
    return row["display_name"] if row else PEOPLE[person]


def serialize_message(row, connection):
    created_at = datetime.fromisoformat(row["created_at"])
    sender_id = row["sender_id"]
    return {
        "id": row["id"],
        "person": sender_id,
        "from": profile_name(connection, sender_id) if sender_id in PEOPLE else row["sender"],
        "text": "This message was deleted." if row["deleted_at"] else row["text"],
        "deleted": bool(row["deleted_at"]),
        "ts": int(created_at.timestamp() * 1000),
        "reactions": row.get("reactions", []) if hasattr(row, "get") else [],
    }


def message_with_reactions(connection, message_id):
    row = connection.execute(
        "SELECT id, sender, sender_id, text, created_at, deleted_at FROM messages WHERE id = ?",
        (message_id,),
    ).fetchone()
    if not row:
        return None
    message = serialize_message(row, connection)
    reactions = connection.execute(
        "SELECT person, emoji FROM reactions WHERE message_id = ? ORDER BY person",
        (message_id,),
    ).fetchall()
    message["reactions"] = [
        {"person": reaction["person"], "emoji": reaction["emoji"]}
        for reaction in reactions
    ]
    return message


@app.get("/")
async def home():
    return FileResponse(BASE_DIR / "index.html")


@app.get("/api/config")
async def get_config():
    numbers = {
        "aditya": os.getenv("ADITYA_WHATSAPP_NUMBER", "919334823399"),
        "tishu": os.getenv("TISHU_WHATSAPP_NUMBER", ""),
    }
    return {
        "whatsapp_numbers": {
            person: "".join(character for character in number if character.isdigit())
            for person, number in numbers.items()
        }
    }


@app.get("/api/auth/session")
async def get_auth_session(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        name = profile_name(connection, person)
    return {"person": person, "name": name}


@app.put("/api/profile/display-name")
async def update_display_name(payload: DisplayNameRequest, request: Request):
    person = authenticated_person(request)
    display_name = payload.display_name.strip()
    if not display_name:
        raise HTTPException(status_code=400, detail="Enter a name before saving.")
    now = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        other = connection.execute(
            "SELECT person FROM profiles WHERE lower(display_name) = lower(?) AND person != ?",
            (display_name, person),
        ).fetchone()
        if other:
            raise HTTPException(status_code=409, detail="That display name is already in use.")
        connection.execute(
            "UPDATE profiles SET display_name = ?, updated_at = ? WHERE person = ?",
            (display_name, now, person),
        )
    await broadcast({"type": "profile_updated", "person": person, "name": display_name})
    return {"ok": True, "person": person, "name": display_name}


@app.get("/api/postcards")
async def get_postcards(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender_id, recipient_id, text, created_at, reveal_at, opened_at "
            "FROM postcards WHERE (sender_id = ? OR recipient_id = ?) AND opened_at IS NULL "
            "ORDER BY created_at DESC, id DESC LIMIT 100",
            (person, person),
        ).fetchall()
        postcards = []
        for row in reversed(rows):
            postcards.append({
                "id": row["id"],
                "from": profile_name(connection, row["sender_id"]),
                "to": profile_name(connection, row["recipient_id"]),
                "text": row["text"] if row["sender_id"] == person else None,
                "sent": row["sender_id"] == person,
                "sent_at": row["created_at"],
                "status": "unread",
            })
    return postcards


@app.post("/api/postcards")
async def create_postcard(payload: PostcardRequest, request: Request):
    sender = authenticated_person(request)
    recipient = "tishu" if sender == "aditya" else "aditya"
    text = payload.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="Write a little note before sending.")
    created_at = datetime.now(timezone.utc)
    sent_at = created_at.isoformat()
    with database() as connection:
        insert_query = (
            "INSERT INTO postcards (sender_id, recipient_id, text, created_at, reveal_at) "
            "VALUES (?, ?, ?, ?, ?)"
        )
        if DATABASE_URL:
            insert_query += " RETURNING id"
        cursor = connection.execute(
            insert_query,
            (sender, recipient, text, sent_at, sent_at),
        )
        postcard_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
        recipient_name = profile_name(connection, recipient)
    await broadcast({"type": "postcard_created", "id": postcard_id, "recipient": recipient})
    return {
        "ok": True,
        "id": postcard_id,
        "recipient": recipient,
        "recipient_name": recipient_name,
    }


@app.post("/api/postcards/{postcard_id}/open")
async def open_postcard(postcard_id: int, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        lock_clause = " FOR UPDATE" if DATABASE_URL else ""
        row = connection.execute(
            "SELECT id, sender_id, recipient_id, text, created_at, reveal_at, opened_at "
            f"FROM postcards WHERE id = ?{lock_clause}", (postcard_id,),
        ).fetchone()
        if not row or row["recipient_id"] != person:
            raise HTTPException(status_code=404, detail="That postcard is not for you.")
        newly_opened = row["opened_at"] is None
        postcard = {
            "id": row["id"],
            "from": profile_name(connection, row["sender_id"]),
            "to": profile_name(connection, row["recipient_id"]),
            "text": row["text"],
            "sent": False,
            "opened": True,
            "newly_opened": newly_opened,
            "status": "opened",
        }
        connection.execute("DELETE FROM postcards WHERE id = ?", (postcard_id,))
    await broadcast({"type": "postcard_removed", "id": postcard_id})
    return postcard


@app.get("/api/settings/welcome-sentence")
async def get_welcome_sentence(request: Request):
    authenticated_person(request)
    with database() as connection:
        row = connection.execute(
            "SELECT setting_value FROM app_settings WHERE setting_key = ?",
            ("welcome_sentence",),
        ).fetchone()
    return {"value": row["setting_value"]}


@app.put("/api/settings/welcome-sentence")
async def update_welcome_sentence(payload: SettingRequest, request: Request):
    person = authenticated_person(request)
    value = payload.value.strip()
    if not value:
        raise HTTPException(status_code=400, detail="The welcome sentence cannot be empty.")
    now = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        if DATABASE_URL:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?) "
                "ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value, updated_at = EXCLUDED.updated_at",
                ("welcome_sentence", value, now),
            )
        else:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?) "
                "ON CONFLICT(setting_key) DO UPDATE SET setting_value = excluded.setting_value, updated_at = excluded.updated_at",
                ("welcome_sentence", value, now),
            )
    await broadcast({"type": "setting_updated", "key": "welcome_sentence", "value": value})
    return {"ok": True, "value": value, "updated_by": person}


@app.post("/api/auth/login")
async def login(payload: LoginRequest, request: Request, response: Response):
    phrase = payload.sentence.strip()
    if not phrase:
        raise HTTPException(status_code=401, detail="That sentence didn't sound quite right.")
    with database() as connection:
        rows = connection.execute(
            "SELECT person, salt, phrase_hash FROM sign_in_phrases"
        ).fetchall()
    matches = [
        row["person"]
        for row in rows
        if phrase_matches(phrase, row["salt"], row["phrase_hash"])
    ]
    if len(matches) != 1:
        raise HTTPException(status_code=401, detail="That sentence didn't sound quite right.")

    person = matches[0]
    matched_row = next(row for row in rows if row["person"] == person)
    token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    with database() as connection:
        if needs_hash_upgrade(matched_row["phrase_hash"]):
            salt, phrase_hash = hash_phrase(phrase)
            connection.execute(
                "UPDATE sign_in_phrases SET salt = ?, phrase_hash = ? WHERE person = ?",
                (salt, phrase_hash, person),
            )
        connection.execute("DELETE FROM sessions WHERE expires_at <= ?", (int(time.time()),))
        connection.execute(
            "INSERT INTO sessions (token_hash, person, expires_at) VALUES (?, ?, ?)",
            (token_hash, person, int(time.time()) + SESSION_SECONDS),
        )
    response.set_cookie(
        SESSION_COOKIE,
        token,
        max_age=SESSION_SECONDS,
        httponly=True,
        secure=request.url.scheme == "https",
        samesite="strict",
        path="/",
    )
    with database() as connection:
        name = profile_name(connection, person)
    return {"person": person, "name": name}


@app.post("/api/auth/logout")
async def logout(request: Request, response: Response):
    token = request.cookies.get(SESSION_COOKIE)
    if token:
        token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        with database() as connection:
            connection.execute("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))
    response.delete_cookie(SESSION_COOKIE, path="/", httponly=True, samesite="strict")
    return {"ok": True}


@app.put("/api/auth/login-sentence")
async def change_login_sentence(payload: ChangeSentenceRequest, request: Request):
    person = authenticated_person(request)
    current_phrase = payload.current_sentence.strip()
    new_phrase = payload.new_sentence.strip()
    with database() as connection:
        rows = connection.execute(
            "SELECT person, salt, phrase_hash FROM sign_in_phrases"
        ).fetchall()
        own_row = next(row for row in rows if row["person"] == person)
        if not phrase_matches(current_phrase, own_row["salt"], own_row["phrase_hash"]):
            raise HTTPException(status_code=400, detail="The current sentence doesn't match.")
        if phrase_matches(new_phrase, own_row["salt"], own_row["phrase_hash"]):
            raise HTTPException(status_code=400, detail="Pick a different sentence this time.")
        for row in rows:
            if row["person"] != person and phrase_matches(new_phrase, row["salt"], row["phrase_hash"]):
                raise HTTPException(status_code=400, detail="That sentence is already theirs. Choose another.")
        salt, phrase_hash = hash_phrase(new_phrase)
        connection.execute(
            "UPDATE sign_in_phrases SET salt = ?, phrase_hash = ? WHERE person = ?",
            (salt, phrase_hash, person),
        )
        token = request.cookies.get(SESSION_COOKIE, "")
        token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        connection.execute(
            "DELETE FROM sessions WHERE person = ? AND token_hash != ?", (person, token_hash)
        )
    return {"ok": True}


@app.get("/api/messages")
async def get_messages(request: Request):
    authenticated_person(request)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender, text, created_at, deleted_at FROM messages ORDER BY id DESC LIMIT 100"
        ).fetchall()
        messages = [message_with_reactions(connection, row["id"]) for row in reversed(rows)]
    return messages


@app.delete("/api/messages/{message_id}")
async def delete_message(message_id: int, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        row = connection.execute(
            "SELECT sender, sender_id, deleted_at FROM messages WHERE id = ?", (message_id,)
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="That message no longer exists.")
        if row["sender_id"] != person:
            raise HTTPException(status_code=403, detail="You can only delete your own messages.")
        if row["deleted_at"]:
            return {"ok": True}
        deleted_at = datetime.now(timezone.utc).isoformat()
        connection.execute(
            "UPDATE messages SET deleted_at = ?, deleted_by = ?, text = ? WHERE id = ?",
            (deleted_at, person, "", message_id),
        )
        message = message_with_reactions(connection, message_id)
    await broadcast({"type": "message_updated", "message": message})
    return {"ok": True, "message": message}


@app.put("/api/messages/{message_id}/reaction")
async def set_reaction(message_id: int, payload: dict, request: Request):
    person = authenticated_person(request)
    emoji = str(payload.get("emoji", "")).strip()
    allowed_emojis = {"❤️", "👍", "😂", "😍", "😢", "😮", "😡", "👏"}
    if emoji and emoji not in allowed_emojis:
        raise HTTPException(status_code=400, detail="That reaction is not available.")
    with database() as connection:
        message = connection.execute(
            "SELECT id, deleted_at FROM messages WHERE id = ?", (message_id,)
        ).fetchone()
        if not message or message["deleted_at"]:
            raise HTTPException(status_code=404, detail="That message is unavailable.")
        now = datetime.now(timezone.utc).isoformat()
        if emoji:
            if DATABASE_URL:
                connection.execute(
                    "INSERT INTO reactions (message_id, person, emoji, created_at, updated_at) VALUES (?, ?, ?, ?, ?) "
                    "ON CONFLICT (message_id, person) DO UPDATE SET emoji = EXCLUDED.emoji, updated_at = EXCLUDED.updated_at",
                    (message_id, person, emoji, now, now),
                )
            else:
                connection.execute(
                    "INSERT INTO reactions (message_id, person, emoji, created_at, updated_at) VALUES (?, ?, ?, ?, ?) "
                    "ON CONFLICT(message_id, person) DO UPDATE SET emoji = excluded.emoji, updated_at = excluded.updated_at",
                    (message_id, person, emoji, now, now),
                )
        else:
            connection.execute(
                "DELETE FROM reactions WHERE message_id = ? AND person = ?", (message_id, person)
            )
        updated_message = message_with_reactions(connection, message_id)
    await broadcast({"type": "message_updated", "message": updated_message})
    return updated_message


connected_clients: set[WebSocket] = set()
broadcast_lock = asyncio.Lock()


async def broadcast(message: dict):
    async with broadcast_lock:
        clients = list(connected_clients)
        results = await asyncio.gather(
            *(client.send_json(message) for client in clients), return_exceptions=True
        )
        for client, result in zip(clients, results):
            if isinstance(result, Exception):
                connected_clients.discard(client)


@app.websocket("/ws/chat")
async def chat_socket(websocket: WebSocket):
    await websocket.accept()
    person = session_person(websocket.cookies.get(SESSION_COOKIE))
    if not person:
        await websocket.close(code=4401, reason="Sign in first.")
        return
    connected_clients.add(websocket)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender, text, created_at, deleted_at FROM messages ORDER BY id DESC LIMIT 100"
        ).fetchall()
        messages = [message_with_reactions(connection, row["id"]) for row in reversed(rows)]
    await websocket.send_json({"type": "history", "messages": messages})
    try:
        while True:
            payload = await websocket.receive_json()
            if session_person(websocket.cookies.get(SESSION_COOKIE)) != person:
                await websocket.close(code=4401, reason="Your sign-in has changed.")
                break
            try:
                message = ChatMessage.model_validate(payload)
            except Exception:
                await websocket.send_json({"type": "error", "message": "That message needs a name and a little less than 300 characters."})
                continue
            text = message.text.strip()
            if not text:
                continue
            created_at = datetime.now(timezone.utc).isoformat()
            with database() as connection:
                sender_name = profile_name(connection, person)
                insert_query = "INSERT INTO messages (sender, sender_id, text, created_at) VALUES (?, ?, ?, ?)"
                if DATABASE_URL:
                    insert_query += " RETURNING id"
                cursor = connection.execute(insert_query, (sender_name, person, text, created_at))
                message_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
                row = connection.execute(
                    "SELECT id, sender, sender_id, text, created_at, deleted_at FROM messages WHERE id = ?", (message_id,)
                ).fetchone()
                saved_message = message_with_reactions(connection, message_id)
            await broadcast({"type": "message", "message": saved_message})
    except WebSocketDisconnect:
        pass
    finally:
        connected_clients.discard(websocket)