import asyncio
import hashlib
import io
import json
import os
import secrets
import time
import urllib.error
import urllib.request
import uuid
import zipfile
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote
from urllib.parse import urlencode
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from fastapi import FastAPI, File, Form, HTTPException, Request, Response, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from argon2 import PasswordHasher
from server.realtime import (
    active_call_routes,
    broadcast,
    connected_clients,
    connected_clients_by_person,
)
from server.db import database
from server.auth import (
    authenticated_person,
    clear_login_failures,
    enforce_login_rate_limit,
    hash_phrase,
    login_failures,
    login_source,
    needs_hash_upgrade,
    phrase_matches,
    profile_name,
    record_login_failure,
    require_owner,
    session_person,
    validate_person,
)
from server.config import (
    ALLOWED_ATTACHMENT_TYPES,
    ALLOWED_ORIGINS,
    BASE_DIR,
    CALL_SIGNAL_ACTIONS,
    DATABASE_PATH,
    DATABASE_URL,
    DEFAULT_LOCATIONS,
    LOGIN_MAX_FAILURES,
    LOGIN_WINDOW_SECONDS,
    MAX_ATTACHMENT_SIZE,
    MAX_CALL_SIGNAL_BYTES,
    MAX_CHAT_ATTACHMENTS,
    PASSWORD_ROUNDS,
    PEOPLE,
    SESSION_COOKIE,
    SESSION_SECONDS,
    VALID_PEOPLE,
)


geocode_lock = asyncio.Lock()
last_geocode_request_at = 0.0


def initialize_db():
    with database() as connection:
        message_id_type = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if DATABASE_URL
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        statements = (
            f"""CREATE TABLE IF NOT EXISTS messages (
                id {message_id_type},
                sender TEXT NOT NULL,
                sender_id TEXT,
                client_message_id TEXT,
                text TEXT NOT NULL,
                created_at TEXT NOT NULL,
                deleted_at TEXT,
                deleted_by TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS sign_in_phrases (
                person TEXT PRIMARY KEY,
                salt TEXT NOT NULL,
                phrase_hash TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                person TEXT NOT NULL,
                expires_at BIGINT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS reactions (
                message_id BIGINT NOT NULL,
                person TEXT NOT NULL,
                emoji TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                PRIMARY KEY (message_id, person)
            )""",
            """CREATE TABLE IF NOT EXISTS app_settings (
                setting_key TEXT PRIMARY KEY,
                setting_value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS profiles (
                person TEXT PRIMARY KEY,
                display_name TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS profile_locations (
                person TEXT PRIMARY KEY,
                city TEXT NOT NULL,
                time_zone TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""",
            f"""CREATE TABLE IF NOT EXISTS postcards (
                id {message_id_type},
                sender_id TEXT NOT NULL,
                recipient_id TEXT NOT NULL,
                text TEXT NOT NULL,
                attachments TEXT NOT NULL DEFAULT '[]',
                created_at TEXT NOT NULL,
                reveal_at TEXT NOT NULL,
                opened_at TEXT
            )""",
            f"""CREATE TABLE IF NOT EXISTS attachments (
                id TEXT PRIMARY KEY,
                uploaded_by TEXT NOT NULL,
                filename TEXT NOT NULL,
                content_type TEXT NOT NULL,
                size BIGINT NOT NULL,
                data {'BYTEA' if DATABASE_URL else 'BLOB'} NOT NULL,
                created_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS attachment_access (
                attachment_id TEXT NOT NULL,
                person TEXT NOT NULL,
                PRIMARY KEY (attachment_id, person)
            )""",
            """CREATE TABLE IF NOT EXISTS call_history (
                call_id TEXT PRIMARY KEY,
                caller_id TEXT NOT NULL,
                recipient_id TEXT NOT NULL,
                mode TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                connected_at TEXT,
                ended_at TEXT,
                duration_seconds INTEGER NOT NULL DEFAULT 0
            )""",
            """CREATE TABLE IF NOT EXISTS hidden_messages (
                message_id BIGINT NOT NULL,
                person TEXT NOT NULL,
                hidden_at TEXT NOT NULL,
                PRIMARY KEY (message_id, person)
            )""",
            "CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at)",
            "CREATE INDEX IF NOT EXISTS idx_reactions_message_id ON reactions (message_id)",
            "CREATE INDEX IF NOT EXISTS idx_postcards_recipient_reveal ON postcards (recipient_id, reveal_at)",
            "CREATE INDEX IF NOT EXISTS idx_call_history_created_at ON call_history (created_at)",
        )
        for statement in statements:
            connection.execute(statement)
        connection.execute("DELETE FROM postcards WHERE opened_at IS NOT NULL")
        if DATABASE_URL:
            existing_columns = {
                row["column_name"]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns WHERE table_name = 'messages'"
                ).fetchall()
            }
            existing_postcard_columns = {
                row["column_name"]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns WHERE table_name = 'postcards'"
                ).fetchall()
            }
        else:
            existing_columns = {
                row["name"]
                for row in connection.execute("PRAGMA table_info(messages)").fetchall()
            }
            existing_postcard_columns = {
                row["name"]
                for row in connection.execute("PRAGMA table_info(postcards)").fetchall()
            }
        if "deleted_at" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN deleted_at TEXT")
        if "deleted_by" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN deleted_by TEXT")
        if "sender_id" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN sender_id TEXT")
        if "client_message_id" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN client_message_id TEXT")
        if "attachments" not in existing_columns:
            connection.execute("ALTER TABLE messages ADD COLUMN attachments TEXT NOT NULL DEFAULT '[]'")
        if "attachments" not in existing_postcard_columns:
            connection.execute("ALTER TABLE postcards ADD COLUMN attachments TEXT NOT NULL DEFAULT '[]'")
        connection.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_sender_client_id "
            "ON messages (sender_id, client_message_id) WHERE client_message_id IS NOT NULL"
        )
        for person, name in PEOPLE.items():
            profile_exists = connection.execute(
                "SELECT 1 FROM profiles WHERE person = ?", (person,)
            ).fetchone()
            if not profile_exists:
                connection.execute(
                    "INSERT INTO profiles (person, display_name, updated_at) VALUES (?, ?, ?)",
                    (person, name, datetime.now(timezone.utc).isoformat()),
                )
            connection.execute(
                "UPDATE messages SET sender_id = ? WHERE sender = ? AND sender_id IS NULL",
                (person, name),
            )
        for person, phrase in (("aditya", "I'm Aditya"), ("tishu", "I'm Tishu")):
            exists = connection.execute(
                "SELECT 1 FROM sign_in_phrases WHERE person = ?", (person,)
            ).fetchone()
            if not exists:
                salt, phrase_hash = hash_phrase(phrase)
                connection.execute(
                    "INSERT INTO sign_in_phrases (person, salt, phrase_hash) VALUES (?, ?, ?)",
                    (person, salt, phrase_hash),
                )
        setting_exists = connection.execute(
            "SELECT 1 FROM app_settings WHERE setting_key = ?", ("welcome_sentence",)
        ).fetchone()
        if not setting_exists:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?)",
                ("welcome_sentence", "A little hello from Delhi", datetime.now(timezone.utc).isoformat()),
            )


@asynccontextmanager
async def lifespan(_app: FastAPI):
    initialize_db()
    yield


app = FastAPI(title="Aditya & Tishu", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Content-Type"],
)


@app.middleware("http")
async def add_security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "DENY")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault(
        "Permissions-Policy", "camera=(self), microphone=(self), geolocation=(self)"
    )
    if request.url.scheme == "https":
        response.headers.setdefault("Strict-Transport-Security", "max-age=31536000")
    return response


class ChatMessage(BaseModel):
    text: str = Field(default="", max_length=300)
    attachments: list[str] = Field(default_factory=list, max_length=4)
    client_id: str | None = Field(default=None, max_length=36)


class LoginRequest(BaseModel):
    sentence: str = Field(min_length=1, max_length=200)


class ChangeSentenceRequest(BaseModel):
    current_sentence: str = Field(min_length=1, max_length=200)
    new_sentence: str = Field(min_length=8, max_length=200)


class SettingRequest(BaseModel):
    value: str = Field(min_length=1, max_length=300)


class DisplayNameRequest(BaseModel):
    display_name: str = Field(min_length=1, max_length=40)


class LocationUpdateRequest(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    time_zone: str = Field(min_length=1, max_length=100)


class PostcardRequest(BaseModel):
    text: str = Field(default="", max_length=500)
    attachments: list[str] = Field(default_factory=list, max_length=1)


def attachment_metadata(connection, attachment_ids: list[str], person: str, limit: int):
    ids = list(dict.fromkeys(attachment_ids))
    if len(ids) > limit:
        raise HTTPException(status_code=400, detail=f"Attach no more than {limit} files.")
    if not ids:
        return []
    placeholders = ", ".join("?" for _ in ids)
    rows = connection.execute(
        f"SELECT id, uploaded_by, filename, content_type, size FROM attachments WHERE id IN ({placeholders})",
        tuple(ids),
    ).fetchall()
    by_id = {row["id"]: row for row in rows}
    if len(by_id) != len(ids) or any(by_id[item]["uploaded_by"] != person for item in ids):
        raise HTTPException(status_code=400, detail="One of those files is unavailable. Please attach it again.")
    return [
        {
            "id": row["id"],
            "name": row["filename"],
            "content_type": row["content_type"],
            "size": row["size"],
        }
        for row in (by_id[item] for item in ids)
    ]


def valid_attachment_data(extension: str, data: bytes):
    if extension == ".jpg" or extension == ".jpeg":
        return data.startswith(b"\xff\xd8\xff")
    if extension == ".png":
        return data.startswith(b"\x89PNG\r\n\x1a\n")
    if extension == ".gif":
        return data.startswith((b"GIF87a", b"GIF89a"))
    if extension == ".webp":
        return len(data) >= 12 and data.startswith(b"RIFF") and data[8:12] == b"WEBP"
    if extension == ".pdf":
        return data.startswith(b"%PDF-")
    if extension == ".txt":
        try:
            data.decode("utf-8")
            return b"\x00" not in data
        except UnicodeDecodeError:
            return False
    if extension == ".docx":
        try:
            with zipfile.ZipFile(io.BytesIO(data)) as document:
                return "word/document.xml" in document.namelist()
        except (OSError, zipfile.BadZipFile):
            return False
    return False


def serialize_message(row, connection):
    created_at = datetime.fromisoformat(row["created_at"])
    sender_id = row["sender_id"]
    return {
        "id": row["id"],
        "person": sender_id,
        "client_id": row["client_message_id"],
        "from": profile_name(connection, sender_id) if sender_id in PEOPLE else row["sender"],
        "text": "This message was deleted." if row["deleted_at"] else row["text"],
        "deleted": bool(row["deleted_at"]),
        "ts": int(created_at.timestamp() * 1000),
        "attachments": json.loads(row["attachments"] or "[]") if not row["deleted_at"] else [],
        "reactions": row.get("reactions", []) if hasattr(row, "get") else [],
    }


def message_with_reactions(connection, message_id):
    row = connection.execute(
        "SELECT id, sender, sender_id, client_message_id, text, created_at, deleted_at, attachments FROM messages WHERE id = ?",
        (message_id,),
    ).fetchone()
    if not row:
        return None
    message = serialize_message(row, connection)
    reactions = connection.execute(
        "SELECT person, emoji FROM reactions WHERE message_id = ? ORDER BY person",
        (message_id,),
    ).fetchall()
    message["reactions"] = [
        {"person": reaction["person"], "emoji": reaction["emoji"]}
        for reaction in reactions
    ]
    return message


@app.get("/")
async def home():
    return FileResponse(BASE_DIR / "index.html")


@app.get("/health")
async def health():
    try:
        with database() as connection:
            connection.execute("SELECT 1").fetchone()
    except Exception as error:
        raise HTTPException(status_code=503, detail="Database is unavailable.") from error
    return {"status": "ok"}


@app.get("/api/call-config")
async def get_call_config(request: Request):
    authenticated_person(request)
    ice_servers = [{"urls": "stun:stun.l.google.com:19302"}]
    turn_urls = [url.strip() for url in os.getenv("CALL_TURN_URLS", "").split(",") if url.strip()]
    turn_username = os.getenv("CALL_TURN_USERNAME", "").strip()
    turn_credential = os.getenv("CALL_TURN_CREDENTIAL", "").strip()
    if turn_urls and turn_username and turn_credential:
        ice_servers.append({
            "urls": turn_urls,
            "username": turn_username,
            "credential": turn_credential,
        })
    return {"ice_servers": ice_servers}


def city_from_address(address: dict):
    city = next((address.get(field) for field in (
        "village", "town", "hamlet", "locality", "suburb", "municipality", "city", "district", "county", "name"
    ) if isinstance(address.get(field), str) and address[field].strip()), None)
    if not city:
        raise HTTPException(status_code=422, detail="A city name could not be found for this location.")
    return city.strip()[:80]


def reverse_geocode_geoapify(latitude: float, longitude: float, api_key: str):
    query = urlencode({
        "format": "geojson",
        "lat": latitude,
        "lon": longitude,
        "limit": 1,
        "lang": "en",
        "apiKey": api_key,
    })
    geocode_request = urllib.request.Request(
        f"https://api.geoapify.com/v1/geocode/reverse?{query}",
        headers={
            "User-Agent": "AdityaAndTishu/1.0 (https://aditya-and-tishu.onrender.com)",
            "Accept": "application/geo+json",
        },
    )
    try:
        with urllib.request.urlopen(geocode_request, timeout=8) as response:
            result = json.load(response)
    except urllib.error.HTTPError as error:
        if error.code == 429:
            raise HTTPException(status_code=503, detail="Geoapify city lookup is busy.") from error
        if error.code in {401, 403}:
            raise HTTPException(status_code=503, detail="Geoapify credentials are unavailable.") from error
        raise HTTPException(status_code=503, detail="Geoapify city lookup is unavailable.") from error
    except (urllib.error.URLError, TimeoutError, ValueError) as error:
        raise HTTPException(status_code=503, detail="Geoapify city lookup is unavailable.") from error
    features = result.get("features") if isinstance(result, dict) else None
    properties = features[0].get("properties") if isinstance(features, list) and features and isinstance(features[0], dict) else None
    if not isinstance(properties, dict):
        raise HTTPException(status_code=422, detail="A city name could not be found for this location.")
    return city_from_address(properties)


def reverse_geocode_nominatim(latitude: float, longitude: float):
    query = urlencode({
        "format": "jsonv2",
        "addressdetails": 1,
        "zoom": 14,
        "lat": latitude,
        "lon": longitude,
    })
    geocode_request = urllib.request.Request(
        f"https://nominatim.openstreetmap.org/reverse?{query}",
        headers={
            "User-Agent": "AdityaAndTishu/1.0 (https://aditya-and-tishu.onrender.com)",
            "Accept-Language": "en",
        },
    )
    try:
        with urllib.request.urlopen(geocode_request, timeout=8) as response:
            result = json.load(response)
    except urllib.error.HTTPError as error:
        if error.code == 429:
            raise HTTPException(status_code=503, detail="OpenStreetMap city lookup is busy.") from error
        raise HTTPException(status_code=503, detail="OpenStreetMap city lookup is unavailable.") from error
    except (urllib.error.URLError, TimeoutError, ValueError) as error:
        raise HTTPException(status_code=503, detail="OpenStreetMap city lookup is unavailable.") from error
    address = result.get("address") if isinstance(result, dict) else None
    if not isinstance(address, dict):
        raise HTTPException(status_code=422, detail="A city name could not be found for this location.")
    return city_from_address(address)


def reverse_geocode_city(latitude: float, longitude: float):
    api_key = os.getenv("GEOAPIFY_API_KEY", "").strip()
    lookup_errors = []
    if api_key:
        try:
            return reverse_geocode_geoapify(latitude, longitude, api_key)
        except HTTPException as error:
            lookup_errors.append(error)
    try:
        return reverse_geocode_nominatim(latitude, longitude)
    except HTTPException as error:
        lookup_errors.append(error)
    if len(lookup_errors) == 1:
        raise lookup_errors[0]
    raise HTTPException(status_code=503, detail="Both city lookup services are busy or unavailable. Please try again.")


async def lookup_approximate_city(latitude: float, longitude: float):
    global last_geocode_request_at
    async with geocode_lock:
        wait_seconds = max(0, 1.1 - (time.monotonic() - last_geocode_request_at))
        if wait_seconds:
            await asyncio.sleep(wait_seconds)
        last_geocode_request_at = time.monotonic()
        return await asyncio.to_thread(reverse_geocode_city, round(latitude, 3), round(longitude, 3))


@app.get("/api/locations")
async def get_profile_locations(request: Request):
    authenticated_person(request)
    locations = {person: dict(location) for person, location in DEFAULT_LOCATIONS.items()}
    with database() as connection:
        rows = connection.execute(
            "SELECT person, city, time_zone, updated_at FROM profile_locations"
        ).fetchall()
    for row in rows:
        locations[row["person"]] = {
            "city": row["city"],
            "time_zone": row["time_zone"],
            "updated_at": row["updated_at"],
        }
    return {"locations": locations}


@app.put("/api/location")
async def update_profile_location(payload: LocationUpdateRequest, request: Request):
    person = authenticated_person(request)
    try:
        ZoneInfo(payload.time_zone)
    except (ZoneInfoNotFoundError, ValueError) as error:
        raise HTTPException(status_code=422, detail="That device time zone is not recognized.") from error
    city = await lookup_approximate_city(payload.latitude, payload.longitude)
    updated_at = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        connection.execute(
            "INSERT INTO profile_locations (person, city, time_zone, updated_at) VALUES (?, ?, ?, ?) "
            "ON CONFLICT (person) DO UPDATE SET city = excluded.city, time_zone = excluded.time_zone, updated_at = excluded.updated_at",
            (person, city, payload.time_zone, updated_at),
        )
    location = {"city": city, "time_zone": payload.time_zone, "updated_at": updated_at}
    await broadcast({"type": "location_updated", "person": person, "location": location})
    return {"person": person, "location": location}


@app.delete("/api/location")
async def clear_profile_location(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        connection.execute("DELETE FROM profile_locations WHERE person = ?", (person,))
    location = dict(DEFAULT_LOCATIONS[person])
    await broadcast({"type": "location_updated", "person": person, "location": location})
    return {"person": person, "location": location}


@app.get("/api/calls")
async def get_call_history(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        rows = connection.execute(
            "SELECT call_id, caller_id, recipient_id, mode, status, created_at, connected_at, ended_at, duration_seconds "
            "FROM call_history WHERE caller_id = ? OR recipient_id = ? "
            "ORDER BY created_at DESC LIMIT 50",
            (person, person),
        ).fetchall()
        calls = [{
            "call_id": row["call_id"],
            "caller_id": row["caller_id"],
            "caller_name": profile_name(connection, row["caller_id"]),
            "recipient_id": row["recipient_id"],
            "recipient_name": profile_name(connection, row["recipient_id"]),
            "mode": row["mode"],
            "status": row["status"],
            "created_at": row["created_at"],
            "connected_at": row["connected_at"],
            "ended_at": row["ended_at"],
            "duration_seconds": row["duration_seconds"],
        } for row in rows]
    return calls


def create_call_history(call_id: str, caller_id: str, recipient_id: str, mode: str):
    created_at = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        connection.execute(
            "INSERT INTO call_history (call_id, caller_id, recipient_id, mode, status, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (call_id) DO NOTHING",
            (call_id, caller_id, recipient_id, mode, "ringing", created_at),
        )


def update_call_history(call_id: str, status: str):
    now = datetime.now(timezone.utc)
    with database() as connection:
        row = connection.execute(
            "SELECT status, connected_at, ended_at FROM call_history WHERE call_id = ?",
            (call_id,),
        ).fetchone()
        if not row or row["ended_at"]:
            return
        if status == "connected":
            connection.execute(
                "UPDATE call_history SET status = ?, connected_at = COALESCE(connected_at, ?) WHERE call_id = ?",
                (status, now.isoformat(), call_id),
            )
            return
        if status == "connecting":
            connection.execute("UPDATE call_history SET status = ? WHERE call_id = ?", (status, call_id))
            return
        if status == "hangup":
            status = "completed" if row["connected_at"] else "failed"
        elif status == "connection_lost":
            status = "dropped" if row["connected_at"] else "failed"
        elif status == "disconnect":
            status = "dropped" if row["connected_at"] else "failed" if row["status"] == "connecting" else "missed"
        duration = 0
        if row["connected_at"]:
            try:
                connected_at = datetime.fromisoformat(row["connected_at"])
                duration = max(0, int((now - connected_at).total_seconds()))
            except (TypeError, ValueError):
                duration = 0
        connection.execute(
            "UPDATE call_history SET status = ?, ended_at = ?, duration_seconds = ? WHERE call_id = ?",
            (status, now.isoformat(), duration, call_id),
        )


@app.get("/api/auth/session")
async def get_auth_session(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        name = profile_name(connection, person)
    return {"person": person, "name": name}


@app.get("/api/profile/display-names")
async def get_display_names(request: Request):
    authenticated_person(request)
    with database() as connection:
        names = {
            row["person"]: row["display_name"]
            for row in connection.execute("SELECT person, display_name FROM profiles").fetchall()
        }
    return {"display_names": names}


@app.put("/api/profile/display-name")
async def update_display_name(payload: DisplayNameRequest, request: Request):
    person = authenticated_person(request)
    display_name = payload.display_name.strip()
    if not display_name:
        raise HTTPException(status_code=400, detail="Enter a name before saving.")
    now = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        other = connection.execute(
            "SELECT person FROM profiles WHERE lower(display_name) = lower(?) AND person != ?",
            (display_name, person),
        ).fetchone()
        if other:
            raise HTTPException(status_code=409, detail="That display name is already in use.")
        connection.execute(
            "UPDATE profiles SET display_name = ?, updated_at = ? WHERE person = ?",
            (display_name, now, person),
        )
    await broadcast({"type": "profile_updated", "person": person, "name": display_name})
    return {"ok": True, "person": person, "name": display_name}


@app.get("/api/postcards")
async def get_postcards(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender_id, recipient_id, text, attachments, created_at, reveal_at, opened_at "
            "FROM postcards WHERE (sender_id = ? OR recipient_id = ?) AND opened_at IS NULL "
            "ORDER BY created_at DESC, id DESC LIMIT 100",
            (person, person),
        ).fetchall()
        postcards = []
        for row in reversed(rows):
            postcards.append({
                "id": row["id"],
                "from": profile_name(connection, row["sender_id"]),
                "to": profile_name(connection, row["recipient_id"]),
                "text": row["text"] if row["sender_id"] == person else None,
                "attachments": json.loads(row["attachments"] or "[]") if row["sender_id"] == person else [],
                "sent": row["sender_id"] == person,
                "sent_at": row["created_at"],
                "status": "unread",
            })
    return postcards


@app.post("/api/postcards")
async def create_postcard(payload: PostcardRequest, request: Request):
    sender = authenticated_person(request)
    recipient = "tishu" if sender == "aditya" else "aditya"
    text = payload.text.strip()
    if not text and not payload.attachments:
        raise HTTPException(status_code=400, detail="Write a little note before sending.")
    created_at = datetime.now(timezone.utc)
    sent_at = created_at.isoformat()
    with database() as connection:
        attachments = attachment_metadata(connection, payload.attachments, sender, 1)
        if any(not item["content_type"].startswith("image/") for item in attachments):
            raise HTTPException(status_code=400, detail="Letters can include one image.")
        insert_query = (
            "INSERT INTO postcards (sender_id, recipient_id, text, attachments, created_at, reveal_at) "
            "VALUES (?, ?, ?, ?, ?, ?)"
        )
        if DATABASE_URL:
            insert_query += " RETURNING id"
        cursor = connection.execute(
            insert_query,
            (sender, recipient, text, json.dumps(attachments), sent_at, sent_at),
        )
        postcard_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
        recipient_name = profile_name(connection, recipient)
    await broadcast({"type": "postcard_created", "id": postcard_id, "recipient": recipient})
    return {
        "ok": True,
        "id": postcard_id,
        "recipient": recipient,
        "recipient_name": recipient_name,
    }


@app.post("/api/postcards/{postcard_id}/open")
async def open_postcard(postcard_id: int, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        lock_clause = " FOR UPDATE" if DATABASE_URL else ""
        row = connection.execute(
            "SELECT id, sender_id, recipient_id, text, attachments, created_at, reveal_at, opened_at "
            f"FROM postcards WHERE id = ?{lock_clause}", (postcard_id,),
        ).fetchone()
        if not row or row["recipient_id"] != person:
            raise HTTPException(status_code=404, detail="That postcard is not for you.")
        newly_opened = row["opened_at"] is None
        postcard = {
            "id": row["id"],
            "from": profile_name(connection, row["sender_id"]),
            "to": profile_name(connection, row["recipient_id"]),
            "text": row["text"],
            "attachments": json.loads(row["attachments"] or "[]"),
            "sent": False,
            "opened": True,
            "newly_opened": newly_opened,
            "status": "opened",
        }
        for attachment_id in message_attachment_ids(row["attachments"]):
            connection.execute(
                "INSERT INTO attachment_access (attachment_id, person) VALUES (?, ?) "
                "ON CONFLICT (attachment_id, person) DO NOTHING",
                (attachment_id, person),
            )
        connection.execute("DELETE FROM postcards WHERE id = ?", (postcard_id,))
    await broadcast({"type": "postcard_removed", "id": postcard_id})
    return postcard


@app.get("/api/settings/welcome-sentence")
async def get_welcome_sentence(request: Request):
    authenticated_person(request)
    with database() as connection:
        row = connection.execute(
            "SELECT setting_value FROM app_settings WHERE setting_key = ?",
            ("welcome_sentence",),
        ).fetchone()
    return {"value": row["setting_value"]}


@app.put("/api/settings/welcome-sentence")
async def update_welcome_sentence(payload: SettingRequest, request: Request):
    person = authenticated_person(request)
    value = payload.value.strip()
    if not value:
        raise HTTPException(status_code=400, detail="The welcome sentence cannot be empty.")
    now = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        if DATABASE_URL:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?) "
                "ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value, updated_at = EXCLUDED.updated_at",
                ("welcome_sentence", value, now),
            )
        else:
            connection.execute(
                "INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES (?, ?, ?) "
                "ON CONFLICT(setting_key) DO UPDATE SET setting_value = excluded.setting_value, updated_at = excluded.updated_at",
                ("welcome_sentence", value, now),
            )
    await broadcast({"type": "setting_updated", "key": "welcome_sentence", "value": value})
    return {"ok": True, "value": value, "updated_by": person}


@app.post("/api/auth/login")
async def login(payload: LoginRequest, request: Request, response: Response):
    source = login_source(request)
    await enforce_login_rate_limit(source)
    phrase = payload.sentence.strip()
    if not phrase:
        await record_login_failure(source)
        raise HTTPException(status_code=401, detail="That sentence didn't sound quite right.")
    with database() as connection:
        rows = connection.execute(
            "SELECT person, salt, phrase_hash FROM sign_in_phrases"
        ).fetchall()
    matches = [
        row["person"]
        for row in rows
        if phrase_matches(phrase, row["salt"], row["phrase_hash"])
    ]
    if len(matches) != 1:
        await record_login_failure(source)
        raise HTTPException(status_code=401, detail="That sentence didn't sound quite right.")

    person = matches[0]
    matched_row = next(row for row in rows if row["person"] == person)
    token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    with database() as connection:
        if needs_hash_upgrade(matched_row["phrase_hash"]):
            salt, phrase_hash = hash_phrase(phrase)
            connection.execute(
                "UPDATE sign_in_phrases SET salt = ?, phrase_hash = ? WHERE person = ?",
                (salt, phrase_hash, person),
            )
        connection.execute("DELETE FROM sessions WHERE expires_at <= ?", (int(time.time()),))
        connection.execute(
            "INSERT INTO sessions (token_hash, person, expires_at) VALUES (?, ?, ?)",
            (token_hash, person, int(time.time()) + SESSION_SECONDS),
        )
    response.set_cookie(
        SESSION_COOKIE,
        token,
        max_age=SESSION_SECONDS,
        httponly=True,
        secure=request.url.scheme == "https",
        samesite="strict",
        path="/",
    )
    with database() as connection:
        name = profile_name(connection, person)
    await clear_login_failures(source)
    return {"person": person, "name": name}


@app.post("/api/auth/logout")
async def logout(request: Request, response: Response):
    token = request.cookies.get(SESSION_COOKIE)
    if token:
        token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        with database() as connection:
            connection.execute("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))
    response.delete_cookie(SESSION_COOKIE, path="/", httponly=True, samesite="strict")
    return {"ok": True}


@app.put("/api/auth/login-sentence")
async def change_login_sentence(payload: ChangeSentenceRequest, request: Request):
    person = authenticated_person(request)
    current_phrase = payload.current_sentence.strip()
    new_phrase = payload.new_sentence.strip()
    with database() as connection:
        rows = connection.execute(
            "SELECT person, salt, phrase_hash FROM sign_in_phrases"
        ).fetchall()
        own_row = next(row for row in rows if row["person"] == person)
        if not phrase_matches(current_phrase, own_row["salt"], own_row["phrase_hash"]):
            raise HTTPException(status_code=400, detail="The current sentence doesn't match.")
        if phrase_matches(new_phrase, own_row["salt"], own_row["phrase_hash"]):
            raise HTTPException(status_code=400, detail="Pick a different sentence this time.")
        for row in rows:
            if row["person"] != person and phrase_matches(new_phrase, row["salt"], row["phrase_hash"]):
                raise HTTPException(status_code=400, detail="That sentence is already theirs. Choose another.")
        salt, phrase_hash = hash_phrase(new_phrase)
        connection.execute(
            "UPDATE sign_in_phrases SET salt = ?, phrase_hash = ? WHERE person = ?",
            (salt, phrase_hash, person),
        )
        token = request.cookies.get(SESSION_COOKIE, "")
        token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        connection.execute(
            "DELETE FROM sessions WHERE person = ? AND token_hash != ?", (person, token_hash)
        )
    return {"ok": True}


@app.get("/api/messages")
async def get_messages(request: Request):
    person = authenticated_person(request)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender FROM messages "
            "WHERE NOT EXISTS (SELECT 1 FROM hidden_messages WHERE message_id = messages.id AND person = ?) "
            "ORDER BY id DESC LIMIT 100",
            (person,),
        ).fetchall()
        messages = [message_with_reactions(connection, row["id"]) for row in reversed(rows)]
    return messages


def message_attachment_ids(attachments_json: str | None):
    try:
        attachments = json.loads(attachments_json or "[]")
    except (TypeError, json.JSONDecodeError):
        return []
    if not isinstance(attachments, list):
        return []
    return [str(item["id"]) for item in attachments if isinstance(item, dict) and item.get("id")]


def cleanup_unreferenced_attachments(connection, attachment_ids: list[str]):
    candidates = set(attachment_ids)
    if not candidates:
        return
    for table in ("messages", "postcards"):
        rows = connection.execute(f"SELECT attachments FROM {table}").fetchall()
        for row in rows:
            candidates.difference_update(message_attachment_ids(row["attachments"]))
            if not candidates:
                return
    for attachment_id in tuple(candidates):
        grant = connection.execute(
            "SELECT 1 FROM attachment_access WHERE attachment_id = ? LIMIT 1",
            (attachment_id,),
        ).fetchone()
        if grant:
            candidates.discard(attachment_id)
    for attachment_id in candidates:
        connection.execute("DELETE FROM attachment_access WHERE attachment_id = ?", (attachment_id,))
        connection.execute("DELETE FROM attachments WHERE id = ?", (attachment_id,))


def attachment_is_accessible(connection, attachment_id: str, person: str, uploaded_by: str):
    message_rows = connection.execute(
        "SELECT messages.attachments, hidden_messages.message_id AS hidden_message_id "
        "FROM messages LEFT JOIN hidden_messages "
        "ON hidden_messages.message_id = messages.id AND hidden_messages.person = ? "
        "WHERE messages.deleted_at IS NULL AND messages.attachments != '[]'",
        (person,),
    ).fetchall()
    has_message_reference = False
    for row in message_rows:
        if attachment_id not in message_attachment_ids(row["attachments"]):
            continue
        has_message_reference = True
        if row["hidden_message_id"] is None:
            return True
    grant = connection.execute(
        "SELECT 1 FROM attachment_access WHERE attachment_id = ? AND person = ?",
        (attachment_id, person),
    ).fetchone()
    if grant:
        return True
    if has_message_reference:
        return False
    return uploaded_by == person


@app.delete("/api/messages/{message_id}/hide")
async def hide_message(message_id: int, request: Request):
    person = authenticated_person(request)
    hidden_at = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        message = connection.execute(
            "SELECT id, deleted_at FROM messages WHERE id = ?", (message_id,)
        ).fetchone()
        if not message or message["deleted_at"]:
            raise HTTPException(status_code=404, detail="That message is unavailable.")
        connection.execute(
            "INSERT INTO hidden_messages (message_id, person, hidden_at) VALUES (?, ?, ?) "
            "ON CONFLICT (message_id, person) DO NOTHING",
            (message_id, person, hidden_at),
        )
    await broadcast({"type": "message_hidden", "message_id": message_id, "person": person})
    return {"ok": True}


@app.post("/api/attachments")
async def upload_attachment(request: Request, file: UploadFile = File(...), upload_id: str = Form(...)):
    person = authenticated_person(request)
    try:
        upload_id = str(uuid.UUID(upload_id))
    except (TypeError, ValueError, AttributeError) as error:
        raise HTTPException(status_code=400, detail="That upload could not be identified. Please try again.") from error
    attachment_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"aditya-tishu-attachment:{person}:{upload_id}"))
    filename = "".join(character for character in (file.filename or "").replace("\\", "/").rsplit("/", 1)[-1] if character.isprintable()).strip()[:120]
    extension = Path(filename).suffix.lower()
    content_type = ALLOWED_ATTACHMENT_TYPES.get(extension)
    if not content_type:
        raise HTTPException(status_code=415, detail="Choose an image, PDF, text file, or DOCX document.")
    with database() as connection:
        existing = connection.execute(
            "SELECT id, uploaded_by, filename, content_type, size FROM attachments WHERE id = ?",
            (attachment_id,),
        ).fetchone()
    if existing:
        if existing["uploaded_by"] != person:
            raise HTTPException(status_code=403, detail="That upload belongs to another account.")
        return {
            "id": existing["id"],
            "name": existing["filename"],
            "content_type": existing["content_type"],
            "size": existing["size"],
        }
    data = await file.read(MAX_ATTACHMENT_SIZE + 1)
    if not data:
        raise HTTPException(status_code=400, detail="That file is empty.")
    if len(data) > MAX_ATTACHMENT_SIZE:
        raise HTTPException(status_code=413, detail="Each attachment must be 10 MB or smaller.")
    if not valid_attachment_data(extension, data):
        raise HTTPException(status_code=415, detail="That file does not match its file type.")
    created_at = datetime.now(timezone.utc).isoformat()
    with database() as connection:
        connection.execute(
            "INSERT INTO attachments (id, uploaded_by, filename, content_type, size, data, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO NOTHING",
            (attachment_id, person, filename or f"attachment{extension}", content_type, len(data), data, created_at),
        )
        row = connection.execute(
            "SELECT id, uploaded_by, filename, content_type, size FROM attachments WHERE id = ?",
            (attachment_id,),
        ).fetchone()
        if not row or row["uploaded_by"] != person:
            raise HTTPException(status_code=409, detail="That upload could not be saved. Please retry.")
    return {
        "id": row["id"],
        "name": row["filename"],
        "content_type": row["content_type"],
        "size": row["size"],
    }


@app.get("/api/attachments/{attachment_id}")
async def get_attachment(attachment_id: str, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        row = connection.execute(
            "SELECT uploaded_by, filename, content_type, data FROM attachments WHERE id = ?", (attachment_id,)
        ).fetchone()
        if not row or not attachment_is_accessible(connection, attachment_id, person, row["uploaded_by"]):
            raise HTTPException(status_code=404, detail="That attachment is no longer available.")
    if not row:
        raise HTTPException(status_code=404, detail="That attachment is no longer available.")
    disposition = "inline" if row["content_type"].startswith("image/") else "attachment"
    filename = row["filename"].replace('"', "").replace("\\", "_")
    fallback_filename = filename.encode("ascii", "ignore").decode("ascii") or "attachment"
    encoded_filename = quote(row["filename"], safe="")
    return Response(
        content=row["data"],
        media_type=row["content_type"],
        headers={
            "Content-Disposition": f'{disposition}; filename="{fallback_filename}"; filename*=UTF-8\'\'{encoded_filename}',
            "X-Content-Type-Options": "nosniff",
            "Cache-Control": "private, no-store",
        },
    )


@app.delete("/api/messages/{message_id}")
async def delete_message(message_id: int, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        row = connection.execute(
            "SELECT sender_id, deleted_at, attachments FROM messages WHERE id = ?", (message_id,)
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="That message no longer exists.")
        if row["sender_id"] != person:
            raise HTTPException(status_code=403, detail="You can only delete your own messages.")
        attachment_ids = message_attachment_ids(row["attachments"])
        deleted_at = datetime.now(timezone.utc).isoformat()
        connection.execute(
            "UPDATE messages SET deleted_at = COALESCE(deleted_at, ?), deleted_by = ?, text = ?, attachments = ? WHERE id = ?",
            (deleted_at, person, "", "[]", message_id),
        )
        connection.execute("DELETE FROM reactions WHERE message_id = ?", (message_id,))
        cleanup_unreferenced_attachments(connection, attachment_ids)
        message = message_with_reactions(connection, message_id)
    await broadcast({"type": "message_updated", "message": message})
    return {"ok": True, "message": message}


@app.delete("/api/messages/{message_id}/permanent")
async def permanently_erase_message(message_id: int, request: Request):
    person = authenticated_person(request)
    with database() as connection:
        lock_clause = " FOR UPDATE" if DATABASE_URL else ""
        row = connection.execute(
            "SELECT sender_id, attachments FROM messages WHERE id = ?" + lock_clause,
            (message_id,),
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="That message no longer exists.")
        if row["sender_id"] != person:
            raise HTTPException(status_code=403, detail="You can only permanently erase your own messages.")
        attachment_ids = message_attachment_ids(row["attachments"])
        connection.execute("DELETE FROM reactions WHERE message_id = ?", (message_id,))
        connection.execute("DELETE FROM hidden_messages WHERE message_id = ?", (message_id,))
        connection.execute("DELETE FROM messages WHERE id = ?", (message_id,))
        cleanup_unreferenced_attachments(connection, attachment_ids)
    await broadcast({"type": "message_removed", "message_id": message_id})
    return {"ok": True, "message_id": message_id}


@app.put("/api/messages/{message_id}/reaction")
async def set_reaction(message_id: int, payload: dict, request: Request):
    person = authenticated_person(request)
    emoji = str(payload.get("emoji", "")).strip()
    allowed_emojis = {"❤️", "👍", "😂", "😍", "😢", "😮", "😡", "👏"}
    if emoji and emoji not in allowed_emojis:
        raise HTTPException(status_code=400, detail="That reaction is not available.")
    with database() as connection:
        message = connection.execute(
            "SELECT id, deleted_at FROM messages WHERE id = ?", (message_id,)
        ).fetchone()
        hidden_message = connection.execute(
            "SELECT 1 FROM hidden_messages WHERE message_id = ? AND person = ?",
            (message_id, person),
        ).fetchone()
        if not message or message["deleted_at"] or hidden_message:
            raise HTTPException(status_code=404, detail="That message is unavailable.")
        now = datetime.now(timezone.utc).isoformat()
        if emoji:
            if DATABASE_URL:
                connection.execute(
                    "INSERT INTO reactions (message_id, person, emoji, created_at, updated_at) VALUES (?, ?, ?, ?, ?) "
                    "ON CONFLICT (message_id, person) DO UPDATE SET emoji = EXCLUDED.emoji, updated_at = EXCLUDED.updated_at",
                    (message_id, person, emoji, now, now),
                )
            else:
                connection.execute(
                    "INSERT INTO reactions (message_id, person, emoji, created_at, updated_at) VALUES (?, ?, ?, ?, ?) "
                    "ON CONFLICT(message_id, person) DO UPDATE SET emoji = excluded.emoji, updated_at = excluded.updated_at",
                    (message_id, person, emoji, now, now),
                )
        else:
            connection.execute(
                "DELETE FROM reactions WHERE message_id = ? AND person = ?", (message_id, person)
            )
        updated_message = message_with_reactions(connection, message_id)
    await broadcast({"type": "message_updated", "message": updated_message})
    return updated_message


async def relay_call_signal(websocket: WebSocket, person: str, payload: dict):
    action = payload.get("action")
    target = payload.get("target")
    call_id = payload.get("call_id")
    data = payload.get("data", {})
    if not isinstance(action, str) or action not in CALL_SIGNAL_ACTIONS or not isinstance(target, str) or target not in VALID_PEOPLE or target == person:
        await websocket.send_json({"type": "call_error", "message": "That call request is not valid."})
        return
    try:
        call_id = str(uuid.UUID(call_id))
    except (TypeError, ValueError, AttributeError):
        await websocket.send_json({"type": "call_error", "message": "That call could not be identified."})
        return
    if not isinstance(data, dict) or len(json.dumps(data).encode("utf-8")) > MAX_CALL_SIGNAL_BYTES:
        await websocket.send_json({"type": "call_error", "message": "That call setup message is too large."})
        return
    if action == "invite" and (not isinstance(data.get("mode"), str) or data["mode"] not in {"audio", "video"}):
        await websocket.send_json({"type": "call_error", "message": "Choose audio or video for the call."})
        return
    if action in {"offer", "answer"}:
        description = data.get("description")
        if not isinstance(description, dict) or description.get("type") != action or not isinstance(description.get("sdp"), str):
            await websocket.send_json({"type": "call_error", "message": "That call description is not valid."})
            return
    if action == "ice" and data.get("candidate") is not None and not isinstance(data.get("candidate"), dict):
        await websocket.send_json({"type": "call_error", "message": "That network candidate is not valid."})
        return

    if action == "invite":
        if call_id in active_call_routes:
            await websocket.send_json({"type": "call_error", "message": "That call is already in progress."})
            return
        create_call_history(call_id, person, target, data["mode"])
        await broadcast({"type": "call_history_changed"})
        recipients = tuple(connected_clients_by_person[target])
        if not recipients:
            update_call_history(call_id, "missed")
            await broadcast({"type": "call_history_changed"})
            await websocket.send_json({"type": "call_signal", "action": "unavailable", "call_id": call_id, "sender": target, "data": {}})
            return
        recipient = recipients[0]
        active_call_routes[call_id] = {person: websocket, target: recipient}
    else:
        route = active_call_routes.get(call_id)
        if not route or route.get(person) is not websocket or target not in route:
            await websocket.send_json({"type": "call_error", "message": "That call is no longer active."})
            return
        recipient = route[target]
    message = {"type": "call_signal", "action": action, "call_id": call_id, "sender": person, "data": data}
    try:
        await recipient.send_json(message)
    except Exception:
        connected_clients.discard(recipient)
        connected_clients_by_person[target].discard(recipient)
        active_call_routes.pop(call_id, None)
        if action == "invite":
            update_call_history(call_id, "missed")
            await broadcast({"type": "call_history_changed"})
            await websocket.send_json({"type": "call_signal", "action": "unavailable", "call_id": call_id, "sender": target, "data": {}})
        return
    if action == "accept":
        update_call_history(call_id, "connecting")
        await broadcast({"type": "call_history_changed"})
    elif action == "connected":
        update_call_history(call_id, "connected")
        await broadcast({"type": "call_history_changed"})
    elif action == "busy":
        update_call_history(call_id, "busy")
        await broadcast({"type": "call_history_changed"})
    elif action == "decline":
        reason = data.get("reason")
        status = "missed" if reason == "no_answer" else "failed" if reason == "media_unavailable" else "declined"
        update_call_history(call_id, status)
        await broadcast({"type": "call_history_changed"})
    elif action == "cancel":
        status = "missed" if data.get("reason") == "no_answer" else "cancelled"
        update_call_history(call_id, status)
        await broadcast({"type": "call_history_changed"})
    elif action == "hangup":
        status = "connection_lost" if data.get("reason") == "connection_lost" else "hangup"
        update_call_history(call_id, status)
        await broadcast({"type": "call_history_changed"})
    if action in {"busy", "decline", "cancel", "hangup"}:
        active_call_routes.pop(call_id, None)


async def notify_call_peer_disconnect(websocket: WebSocket, person: str):
    for call_id, route in list(active_call_routes.items()):
        if route.get(person) is not websocket:
            continue
        active_call_routes.pop(call_id, None)
        update_call_history(call_id, "disconnect")
        await broadcast({"type": "call_history_changed"})
        peer_person = "tishu" if person == "aditya" else "aditya"
        peer = route.get(peer_person)
        if not peer:
            continue
        try:
            await peer.send_json({
                "type": "call_signal",
                "action": "peer_disconnected",
                "call_id": call_id,
                "sender": person,
                "data": {},
            })
        except Exception:
            connected_clients.discard(peer)
            connected_clients_by_person[peer_person].discard(peer)


@app.websocket("/ws/chat")
async def chat_socket(websocket: WebSocket):
    await websocket.accept()
    person = session_person(websocket.cookies.get(SESSION_COOKIE))
    if not person:
        await websocket.close(code=4401, reason="Sign in first.")
        return
    connected_clients.add(websocket)
    connected_clients_by_person[person].add(websocket)
    with database() as connection:
        rows = connection.execute(
            "SELECT id, sender FROM messages "
            "WHERE NOT EXISTS (SELECT 1 FROM hidden_messages WHERE message_id = messages.id AND person = ?) "
            "ORDER BY id DESC LIMIT 100",
            (person,),
        ).fetchall()
        messages = [message_with_reactions(connection, row["id"]) for row in reversed(rows)]
    await websocket.send_json({"type": "history", "messages": messages})
    try:
        while True:
            payload = await websocket.receive_json()
            if session_person(websocket.cookies.get(SESSION_COOKIE)) != person:
                await websocket.close(code=4401, reason="Your sign-in has changed.")
                break
            if isinstance(payload, dict) and payload.get("type") == "call_signal":
                await relay_call_signal(websocket, person, payload)
                continue
            try:
                message = ChatMessage.model_validate(payload)
            except Exception:
                await websocket.send_json({"type": "error", "message": "That message needs a name and a little less than 300 characters."})
                continue
            text = message.text.strip()
            if not text and not message.attachments:
                continue
            created_at = datetime.now(timezone.utc).isoformat()
            try:
                with database() as connection:
                    attachments = attachment_metadata(connection, message.attachments, person, MAX_CHAT_ATTACHMENTS)
                    sender_name = profile_name(connection, person)
                    existing = None
                    if message.client_id:
                        existing = connection.execute(
                            "SELECT id FROM messages WHERE sender_id = ? AND client_message_id = ?",
                            (person, message.client_id),
                        ).fetchone()
                    if existing:
                        message_id = existing["id"]
                    else:
                        if message.client_id:
                            insert_query = (
                                "INSERT INTO messages (sender, sender_id, client_message_id, text, attachments, created_at) "
                                "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING"
                            )
                            parameters = (sender_name, person, message.client_id, text, json.dumps(attachments), created_at)
                        else:
                            insert_query = "INSERT INTO messages (sender, sender_id, text, attachments, created_at) VALUES (?, ?, ?, ?, ?)"
                            parameters = (sender_name, person, text, json.dumps(attachments), created_at)
                        if DATABASE_URL:
                            insert_query += " RETURNING id"
                        cursor = connection.execute(insert_query, parameters)
                        if message.client_id:
                            saved_row = connection.execute(
                                "SELECT id FROM messages WHERE sender_id = ? AND client_message_id = ?",
                                (person, message.client_id),
                            ).fetchone()
                            if not saved_row:
                                raise HTTPException(status_code=409, detail="That message could not be saved. Please retry.")
                            message_id = saved_row["id"]
                        else:
                            message_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
                    saved_message = message_with_reactions(connection, message_id)
            except HTTPException as error:
                await websocket.send_json({"type": "error", "message": error.detail})
                continue
            await broadcast({"type": "message", "message": saved_message})
    except WebSocketDisconnect:
        pass
    finally:
        await notify_call_peer_disconnect(websocket, person)
        connected_clients.discard(websocket)
        connected_clients_by_person[person].discard(websocket)